# Generated by Django 3.2.6 on 2021-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matcher', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='person', max_length=100),
        ),
    ]
