# Generated by Django 3.2.6 on 2021-08-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matcher', '0003_candidate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
    ]
